baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false


[params]
    description = "Terrassa is a simple, fast and responsive theme for Hugo with a strong focus on accessibility made from scratch."
    favicon = "favicon.ico"
    logo = ""

[params.hero]
    textColor = "" # Empty for default color

[params.cta] # Call To Action
    show = true
    cta = "What is this all about?"
    link = "#giving-flat-seekers-the-facts-connecting-people-to-each-other" # Relative URL

[params.separator] # Separators between sections on the home page
    show = false

[params.fa] # Font Awesome options
    version = "5.7.2"
    integrity = "sha384-0pzryjIRos8mFBWMzSSZApWtPl/5++eIfzYmTgBBmXYdhvxPc+XcFEk+zJwDgWbP"

[params.form] # Contact form
    netlify = true
    action = "https://formspree.io/your@email.com"
    method = "POST"
    inputNameName = "name"
    inputNameLabel = "Name"
    inputNamePlaceholder = "Your name"
    inputEmailName = "email"
    inputEmailLabel = "Email"
    inputEmailPlaceholder = "Your email"
    inputMsgName = "message"
    inputMsgLabel = "Write something"
    inputMsgLength = 750
    inputSubmitValue = "Send"

[params.posts]
    showAuthor = true
    showDate = true
    showTags = true
    dateFormat = "Monday, Jan, 2006"

[params.contact] # Contact info
    email = ""
    phone = ""
    skype = ""
    address = ""



[params.copy] # Copyright
    copy = "" # Empty for default content

[privacy]
    [privacy.googleAnalytics]
        anonymizeIP = true
        disable = false
        respectDoNotTrack = true
        useSessionStorage = false
    [privacy.instagram]
        disable = false
        simple = false
    [privacy.twitter]
        disable = false
        enableDNT = true
        simple = false
    [privacy.vimeo]
        disable = false
        simple = false
    [privacy.youtube]
        disable = false
        privacyEnhanced = true

[params.languageSwitcher]
    show = true

[languages]
    [languages.en]
        disabled = false
        languageCode = "en"
        languageDirection = "ltr"
        title = "Tenants Support Forum"
        languageName = "en"
        weight = 1
        contentDir = "content"
      [languages.de]
        languageName = "de"
        weight = 2
        contentDir = "content/de"
        languageCode = "de"
        languageDirection = "ltr"
        title = "Tenants Support Forum"
        description = "Das ist die deutsche Beschreibung"
        [languages.de.params]
          [languages.de.params.form] # Translate contact form fields
            inputNameLabel = "Name"
            inputNamePlaceholder = "Dein Name"
            inputEmailLabel = "E-mail"
            inputEmailPlaceholder = "Deine E-Mail-Adresse"
            inputMsgLabel = "Schreib etwas"
            inputSubmitValue = "Abschicken"
            [languages.de.params.cta] # Translate Call To Action
                show = true
                cta = "Kontakt"
                link = "de/kontakt/" # Relative URL
